---
classes:
  - service.git.client
#  - system.linux.system.single
  - system.linux.system.repo.mcp.salt
#  - system.salt.master.api
#  - system.salt.master.pkg
#  - system.reclass.storage.salt
#  - system.salt.minion.ca.salt_master
#  - system.salt.minion.cert.proxy
#  - system.mysql.client.single
parameters:
  _param:
    reclass_data_repository: local
    salt_master_environment_repository: "https://github.com/tcpcloud"
    salt_master_environment_revision: master
    salt_master_host: 192.168.10.100
    salt_master_base_environment: prd
    salt_minion_ca_host: cfg01.kube-deploy.local
    cluster_domain: kube-deploy.local
    #yamllint disable-line rule:line-length
    salt_api_password_hash: "$6$sGnRlxGf$al5jMCetLP.vfI/fTl3Z0N7Za1aeiexL487jAtyRABVfT3NlwZxQGVhO7S1N8OwS/34VHYwZQA8lkXwKMN/GS1"
  linux:
    network:
      interface:
        single_int:
          enabled: true
          name: ens4
          type: eth
          proto: static
          address: 172.16.10.100
          netmask: 255.255.255.0
  salt:
    master:
      file_recv: true
  reclass:
    storage:
      data_source:
        engine: local
      node:
        kube01:
          name: kube01
          domain: ${_param:cluster_domain}
          params:
            linux_system_codename: xenial
            salt_master_host: 192.168.10.100
            single_address: 172.16.10.104
          classes:
            - system.docker.client
            - system.docker.host
        kube02:
          name: kube02
          domain: ${_param:cluster_domain}
          params:
            linux_system_codename: xenial
            salt_master_host: 192.168.10.100
            single_address: 172.16.10.105
